import Menu from "./componente/Menu"
import Footer from "./componente/Footer"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      
      <body>
        <Menu/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
